# Generated by Django 4.1.4 on 2022-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('client_admin_site', 'Add permissions to Client admin site'),),
                'managed': False,
            },
        ),
    ]
