# Generated by Django 4.1.4 on 2022-12-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseadminconfig',
            options={'managed': False, 'permissions': (('client_admin_site', 'User should have access to the Client Admin'),)},
        ),
    ]
